WITH CTE AS (
SELECT 
    TRY_TO_TIMESTAMP(STARTED_AT) AS STARTED,
    DATE(TRY_TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TRY_TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    DAYOFWEEK(TRY_TO_TIMESTAMP(STARTED_AT)) AS DAY_OIF_WEEK,
    CASE
    WHEN DAYNAME(TRY_TO_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun')
    THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
    END AS DAY_TYPE,
    CASE
    WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) IN (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) IN (6,7,8) 
    THEN 'SUMMER'
    ELSE 'AUTUMN'
    END AS STATION_OF_YEAR
from 
{{ source('demo', 'bike') }}


)
select
* from CTE